stencila/thema

src/themes/stencila/styles.css
This makes some small adjustments to `figure` styling. This is needed now to improve the styling of `CodeChunks` which can have more that one figure in its `ouputs` including `pre` and `img`. I'd like to merge this soon for use in demos.
=> fix(Stencila theme): Improve display of figures

package-lock.json, package.json, src/index.ts, tsconfig.json
Changes made to support https://github.com/stencila/encoda/issues/245
These changes allow for exporting a `themes` object which can be consumed from other projects (Encoda in this case).
This has the benefit that available themes are updated in Thema, and reduces chances of trying to access themes unavailable in the installed version of Thema.
A secondary function `getTheme` is exported which allows for looking up a theme by an optional string value, falling back to the `stencila` theme in case the theme isn't found.
---
@jwijay Feel free to merge your PR (#10) first if it's not going to take long, these changes should be simple for me to re-apply on top of your changes if needed.
=> Generate TS declarations & export theme names

src/common/js/index.ts, src/common/styles/common.css, src/common/styles/selectors.css, src/designa/mixins/CreativeWork.css, src/themes/eLife/styles.css, src/themes/nature/styles.css, src/themes/plos/styles.css
---
---
---
---
---
---
---
---
---
Updated encoda output (authors wrapped in `divs`) caused some reference styles to break.
---
---
=> Theme updates

src/common/styles/common.css
Prevents `pre` elements from being incredibly tall when rendered inside iFrames, such as on /Open
=> fix(Pre): Fix Safari bug with rendering Pre elements inside iFrames

src/examples/simple.html, src/themes/stencila/styles.css
=> Fix vertical spacing for nested lists after paragraphs

package.json
The `build:selectors` script has been renamed to [`generate:selectors`](https://github.com/stencila/thema/blob/next/package.json#L12). This change allows the pre-commit hook to run the renamed script.
=> Match pre-commit script name to renamed script

.travis.yml
Once this is merged, we can enable both [`Build pushed branches` and `Build pushed pull requests`](https://docs.travis-ci.com/user/web-ui/#build-pushed-branches) without ending up with [double builds](https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests).
Relates to https://github.com/stencila/thema/pull/45#issuecomment-585806053, as @davidcmoulton PR was not built by the CI.
=> Run CI on forks

src/themes/elife/styles.css
A straightforward CSS change to override the `float-left` brought in from [eLife's `.grid__item` definition](https://github.com/elifesciences/pattern-library/blob/develop/assets/sass/layout/_grid.scss#L323).
I've got a few questions as this is the first PR I've put in to change the theme. Let me know if you'd prefer me to raise these as one or more issues instead of having them here:
- Is `next` the correct branch to merge this into? I'm not sure when to target  `next` vs `master`.
- Running the visual regression tests locally I see the expected layout change in the the screenshot generated in `/test/screenshots/diff/`, but this is registering as a test failure; I guess I need to regenerate the reference screenshot now it's a desired visual change? How is this handled in CI?
- Once it's …
=> Horizontally centre eLife article

.prettierignore, package.json, src/demo/index.ts, src/extensions/code/index.ts, src/extensions/pages/README.md, src/index.ts, src/scripts/dom.ts, src/scripts/themes.ts, src/themes/index.ts, src/themes/rpng/README.md, src/themes/themes.ts, tsconfig-lib.json, tsconfig.json, webpack.config.js
=> Separate browser and lib distributions

src/themes/elife/styles.css
- uses the Person extension css to style the article's author list
- adds eLife-specific overrides where necessary
- *hides affiliation indicator until requirement is clear*
=> eLife authors

postcss.config.js, src/themes/elife/styles.css
Styles an article's authors' affiliations block to match eLife's journal style.
Requested review as it's not restricted to eLife only code due to https://github.com/stencila/thema/compare/style-affiliations?expand=1#diff-b19118abc8e2dbd959e8a14a8c0edcd7R25. `postcss-mixin` was no longer loaded, but was still included in the `package.json`. Reintroducing doesn't have a noticeable impact on the build time locally.
=> Reintroduce postcss-mixin and style eLife affiliations

src/themes/elife/index.ts
- Only affects eLife theme code
- May need to be more defensive & also have tests (hence draft for now).
Before:
After:
Going with Typescript for the theme logic here. If it causes a problem though we can use js instead.
=> Transform article publication date to eLife format

package-lock.json, package.json, src/demo/utils/theme.ts, src/themes/rpng/index.ts, src/themes/rpng/styles.css
This PR adds missing missing Stencila Components scripts to demo iframe, as well as adds logic for hiding the `CodeChunk` source code panel in the RPNG theme.
The loaded RPNG theme now looks like this:
=> Add missing Stencila Components scripts to demo view

package-lock.json, package.json, src/themes/bootstrap/styles.css, src/themes/elife/styles.css, src/themes/galleria/styles.css, src/themes/nature/styles.css, src/themes/plos/styles.css, src/themes/skeleton/styles.css, src/themes/wilmore/styles.css
Closes #113.
Encoda now encodes an `Article`'s `properties` as a `<ul>` after `datePublished`:
All the themes will need to be updated to either display them better or `display: none`r. Ideally that would be done as part of this PR. @davidcmoulton @alex-ketch would you be able to do that and merge this?
=> chore(Deps): Upgrade Encoda

src/themes/elife/index.ts
- Updates custom selector used to target the publication date (`:--datePublished`)
- Doesn't return early from `ready` if the date selector is not available
=> Update eLife's date handling to match Encoda

src/themes/elife/custom-properties.css, src/themes/elife/styles.css
First pass for initial styling
=> feat: Add eLife styling for publication date

.travis.yml
Attempts to fix Documentation site generation by not discarding build artifacts during CI `pages` step.
=> build(Docs): Don't discard build artifacts when deploying Docs

src/browser/index.ts
This was due to an upstream issue with naked imports not resolving correctly when running in Jest. https://github.com/kulshekhar/ts-jest/issues/1149
closes #144 
If you've got the time, could you check that this fixes the issue for you @davidcmoulton please?
Otherwise I'll merge this PR later today. Thanks
=> Fix test run failures

src/themes/elife/downloads.ts
Fixes a bug where the Download list was appended to the bottom of the references section rather than in its own section.
=> fix(Elife): Move downloads into own section

src/examples/examples.ts, src/scripts/examples.ts
This adds https://elifesciences.org/articles/30274v2 as an example.
It is necessary to run `npm run update:examples` to generate the article's HTML locally.
I have tested quickly using `npm run dev` and the example is loading and all seems well.
I have not yet transformed any of the figures into `<stencila-code-chunk>` elements. I plan to do that in the example generation script by replacing certain JSON nodes or HTML elements.
@davidcmoulton or @discodavey please feel free to merge this if it's useful to you. I can add the code chunks either in this PR or another either way.
=> chore(Examples): Add additional eLife article

src/themes/elife/styles.css
Updates the link to import the eLife CSS from the eLife journal site. Required because every time that's updated the URI changes (cache busting).
This will no longer be necessary when eLife's css is available as an `npm`-installable dependency.
=> chore(Elife): Update URI to eLife style import

src/examples/articleReplicationFigure2.R, src/examples/articleReplicationFigure3.R, src/scripts/examples.ts
This adds some example `CodeChunk` and `CodeExpression` nodes to the example that is based on https://elifesciences.org/articles/30274. There are already examples of these node types in the `kitchenSink` example. However, this PR creates further examples that are:
1. in the context of a fully fledged research article
2. have the actual code used to generate the figures (which are often long, c.f. other 'toy' examples)
The approach taken is do the 'enrichment' algorithmic-ally so that this article can continue to be updated as Encoda is updated e.g. 
https://github.com/stencila/thema/blob/941a4fa4b72ff24bbc500a001d704107aea2e555/src/scripts/examples.ts#L104-L115
For some of the themes, executable elements look OK (but could do with some improvements), but in the eLife theme in particular, …
=> chore(Examples): Add executable nodes to the articleReplication example

test/screenshot.test.ts
Don't run visual regression tests if the build folder doesn't exists.
This avoids burying the instruction to run `npm run docs` in other error reports.
**Before:** the errors from other tests would obscure the first error:
**After:**
⚠️ This PR will likely fail until https://github.com/stencila/thema/pull/169 is merged
=> test(WDIO): Don't run tests if the build folder doesn't exist close #167

package-lock.json, package.json
This PR upgrades the ` @stencila/encoda` dependency, thereby bringing several improvement to the HTML generated for the examples. 
```bash
npm install
npm run update:examples
npm run dev
```
These are now encoded in the HTML and can be styled using the `:--label` custom selector:
These are now encoded in the HTML properly:
@discodavey Please feel free to merge at your leisure.
=> chore(Deps): Upgrade Encoda to v0.93.11

package-lock.json, package.json
This PR updates the version of Encoda used to generate the examples (there appears to be a silent bug in Encoda that makes it necessary to run `npm run update:examples` twice to actually get the updated HTML; I think @discodavey may have [encountered this before](https://github.com/stencila/encoda/issues/560#issuecomment-632562361) )
The main reason for this upgrade is to add `data-usage="figGroup"` to `Collection`s used for figure groups so that they can be styled correctly.
```html  
<ol itemscope="" itemtype="http://schema.org/Collection" data-usage="figGroup">
<li>
<figure itemscope="" itemtype="http://schema.stenci.la/Figure" id="fig1" title="Figure 1.">
<label data-itemprop="label">Figure 1.</label><img
src="articleDrosophila.html.media/fig1.jpg" alt="" itemscope="" …
```
=> fix(Deps): Upgrade Encoda

src/themes/stencila/styles.css
Adds border and background colour to tables in Stencila theme.
I'm also about to create an issue in Encoda to propose wrapping Table elements in a container element to facilitate styling overflow/scrollable tables when they have lots of cells.
Current: https://schema.stenci.la/cite
Updated:
=> feat(Stencila): Style Table rows for better readability

src/themes/elife/index.ts, src/themes/elife/lib/contentHeader.ts, src/themes/elife/lib/downloads.ts, src/themes/elife/lib/preHeader.ts, src/themes/elife/styles.css
We need to introduce other elements before the header so it makes sense to swap the `download-link-wrapper` for a more generic wrapper.
=> refactor(Elife): introduce generic pre-header-wrapper

src/themes/elife/lib/dataProvider.ts, src/themes/elife/lib/query.ts, src/themes/elife/test/dataProvider.test.ts, src/themes/elife/test/query.test.ts
This refactor should improve our ability to test the dataProvider functions that rely on query.
=> refactor(Elife): move query into separate module

webpack.config.js
Followup to https://github.com/stencila/thema/pull/220 to fix assets paths when served over CDN.
=> Make static asset paths relative so they work on CDNs

README.md, src/util/index.test.ts, src/util/index.ts
This new test demonstrates that the wrap function only works as expected if you want to wrap an element without children.
If this is the expected behaviour I think we should amend the documentation.
cc @alex-ketch
=> fix: wrap isn’t work if element has children

src/themes/elife/staticCustomProperties.css, src/themes/elife/styles.css
In testing the Hub integration, I noticed that the icons were failing to load.
Turns out it was due to the usage of CSS variables in `url` properties. This causes the path resolution to happen from the URL being viewed, rather than the URL from which the CSS is served.
This is why the icons load in development/Thema gallery site, but fail when served from a different domain such as the Stencila Hub/eLife Hub subdomain.
I've refactored the styles to inline the URLs as needed. Could you review these changes please @nlisgo / @discodavey, thanks.
Edit: Seems to only be an issue in Safari (desktop & iOS)
=> fix(Elife): Don't use string variables in URLs

src/themes/elife/stencilaComponents.css
This PR vertically aligns the button labels, which I've tested locally as currently Thema doesn't inject the executable document toolbar but I've logged an issue to add this functionality in the near future.
cc. @chugginselifesciences
=> fix(ELife): Vertically center button labels

src/themes/elife/index.ts
There is a bug in the implementation. The links contain the doi where they should only contain the manuscript id.
https://facebook.com/sharer/sharer.php?u=https%3A%2F%2Felifesciences.org%2Farticles%2F10.7554%2FeLife.30274%2Fexecutable
it should be:
https://facebook.com/sharer/sharer.php?u=https%3A%2F%2Felifesciences.org%2Farticles%2F30274%2Fexecutable
=> bug(Elife): correct the social link url

src/themes/elife/index.ts, src/themes/elife/lib/externalLinks.ts
Without this fix and external links that are accessed within an iframe will break.
This fix targets all links that have a `href` attribute that starts with `http` that don't currently have a `target` attribute set. It then sets a `target` attribute of `_parent`.
=> bug(Elife): set target _parent on external links

src/themes/elife/lib/downloads.ts
Currently we are linking to an old labs post and have a redirect in place. This will allow us to restore the old labs post.
=> feat(Elife): link to the new labs post directly

.travis.yml, tsconfig.browser.json
This PR addresses two issues:
- The most recent PR was marked as successful on the branch, but [failed on main branch](https://github.com/stencila/thema/runs/1321924038). This was due to the `build` task only running after the merge
- The actual failure was due to `fs-extra` TypeScript definition file throwing a (rightful) error that the browser context doesn't have a `fs` namespace. The [`skipLibCheck` setting](https://www.typescriptlang.org/tsconfig#skipLibCheck) only validates the types used in the browser files, versus across all type definition files present in the project.
=> Catch errors before marking build as successful

src/themes/elife/styles.css
Adds a command and space before the `parentOrganization` property. Avoids the lack of space e.g. in https://hub.stenci.la/elife/article-43154/snapshots/25
I have not had time to test this yet. @nlisgo would appreciate it if you could check it.
=> fix(eLife): Add comma and space before parentOrganization

src/themes/rpng/styles.css
This make the affordances on `CodeChunks` and `CodeExpressions` in RNGs much more subtle, showing only a green dot in the top left corner (middle-left for expressions) and reducing whitespace around them. The intent is to create images that are close to those that will appear in a published article but with an indicator that something can be done with them. In the future we might use a red square instead for code elements that have an error on them.
I have done more realistic tests going from `ipynb` to `docx` to `gdoc` and am happy with the final result: (note that the size of the "no output" dot is larger in the `docx` when Pandoc generates that file, maybe has some minimum size on images?)
=> fix(RPNG): Increase subtedly of affordance

package-lock.json, package.json
This PR attempts to fix the build. It branches off v2.20.7 the last release. Doing this now because I have some fixes to RPNG that I'd very much like to deploy soon.
The issue is that the https://github.com/stencila/postcss-import-url no longer exists (it was deleted ~4days ago):
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/stencila/postcss-import-url.git
npm ERR! 
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/stencila/postcss-import-url.git/'
npm ERR! 
npm ERR! exited with error code: 128
```
Using the latest version of `postcss-import-url` doesn't work https://github.com/stencila/thema/commit/f4c8bba50f54bc867be4790dfb0dfb7e671443a7#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346 …
=> fix(Deps): Use postcss-import-url v5.1.0

.stylelintrc, src/extensions/cite-apa/styles.css, src/extensions/cite-numeric/styles.css, src/themes/elife/styles.css
This PR follows up on #295 to style `Cite` elements outside of `CiteGroup`s.
There will likely be future refinements, in coordination with Encoda changes, to avoid having double brackets around numeric in-text citations.
=> Format in-text citations outside of CiteGroups

src/examples/articleKitchenSink.json, src/lib/index.ts, src/themes/rpng/styles.css
This is a follow up to https://github.com/stencila/thema/pull/294 and ensures that the contents of all types of executable nodes are fully visible.
Additionally it exposes a helper function to get the dimensions of the RPNG symbol, allowing usage from Encoda to then crop the symbol as necessary when decoding RPNGs to other formats.
Corresponding PR in Encoda: https://github.com/stencila/encoda/pull/836
=> RPNG icon repositioning

README.md, src/extensions/cite-apa/styles.css, src/extensions/cite-author-year/README.md, src/extensions/cite-author-year/styles.css, src/extensions/cite-mla/styles.css, src/themes/elife/README.md, src/themes/elife/styles.css, test/selectors.test.ts
This fixes #314. It doing so it factors out the styling of author-year style citations into a new extension `cite-author-year` that is a counterpart of `cite-numeric`. This was done in anticipation of wanting to add more subtle styling variations based the `citationMode` property. See https://github.com/stencila/schema/pull/247.
=> Factor out cite-author-year extension; use in eLife theme
